name: giffy_dialog
description: A Flutter package for a quick, handy and beautiful giffy dialog.
version: 2.0.0
homepage: https://github.com/xsahil03x/giffy_dialog

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0

flutter: